sudo: false
language: ruby
rvm:
- 2.3.1
before_install: gem install bundler -v 1.12.5
deploy:
  provider: rubygems
  api_key:
    secure: NPlfRLnutld0AO4T0ExzxqIojeQVt+JIMWPp2NE4vincN+arKwlg+bEp2hwl1tNZZ/UPk4ZMGf7XScYxXIe4QcQPwdsHoiuehJ/KpwewXR2aSh3WDXr7ZoPYnvVzFODq+QSexIqGDyis5qWLax+ooF907nVGWNzDWpjkzoi0biKMPqUOBO06Xl/olGRpRTBW+VZCGR/uSfBvgJpNFJ1zxvldcSHWszk5NL54FrrLxWibKDTu0r0mMxJrPS6toA4ynBEW8A1zVA5IuRrD/VLmYIeh6VDYczFCXyCbd1Fi95ak8j/GzMTOpyR6NgmYycxWtk6K+K//ULoD+P4QYF1MLKeb5GaqBElUWWo9JyFrrlHk6DfAOEPsdSikvcFnkUNtL1dXEn7hsNcG7yR22oVFgNg+6bj371bwZJxTe/FpRH0gIrT5X7zJ2UpkusEvWzdIm9ToaWAOtb4UsF908QndGoKjBor7zi4CX5FeIHPwVHu1PlRoq+rM1BMA1vTARh6HzHy8Qtjh9Y1j5ZKJ8b4hORubnp4cvFjIlmLmvizICddb2ukHHRNxL1LwEEzz4s2ikxqdkZ0OwgkaJGVkYa7h1Wj2ii+yb0Ol4i1vajmRFCRRV6sT3OZqqBz2UCrQJYQv7sycO7hkmNBdNuaNWQcltPm5KYPDYg5xyip0hxZoFk4=
  gem: zammad_api
  on:
    tags: true
    repo: zammad/zammad-api-client-ruby
